apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEF6TXpBeQpNakEzTkRWYUZ3MDBNVEF6TXpBeU1qQTNORFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDdDJXNURzUkdwWDN2elRlZTVrbmNHUEJaQUFtcXBMZzF4dHhEcEdQcVlLM1ZSRnlpbgorSm11dFBMeWc5S0EzZ3doQlRzNHpkckt4a1hXeTJ0RmFoWWs3UWpqNnFpKzV6Q3NFMi9MenNraUptQ3lvTzc1CjZIRjJVRi9qUUV1SkFPeWd3OGNySk0wd2RLRE8wL0lHNEgzR2p1TlJjNjBWQy94b2RMQWZabk91Wlozc3RGQ24KbzNSRFpkTzVmMWtRTHVOem1sVEc4QjNSSjB3d2N2d1F6TFEzWjhDWEZSTDRiRlYxSEpFYklQbWJPTmhqZzcxUwppbDBtbkhFTWJxTlFRNGtDbkF1RGhRWWYzRVU3S1FMM0g0bHlNWTFMbmlXT3RiTCtrMjRSR08zQTQxQ0c5M3N1CmJTQVpvcVlCQTJMV0ZrWXFvMkZ6MXE1VzFPRU9OS3Q4OXlwL0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlQwNlZqYk1Gbkd4WTFxbDR6ZwpQWjRIQTM5c3lUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsclZLdktrbkVJKzhNWjlzcGVGdmNUNHBwb0ZNCkgxNXpPMWhkeksydHlqYnJmYW1pSXlzbmJaOWVPMGt6djdBcHV4T0Q5VDF1L2d0SWVsMjJ2ZUtRclRpNzIvVGQKaFBacTZYT2NoS0dsTHBUN295ZkkzSC82Q29RWGdZRUFBZmxPb0hiaFppQnB3dWRzR2JRaDB3OVhpekZ1WjNjcwpIZzFadGExclF4V1dvc2tIV0NsRWZ4QUhaY05LYUFWbStNZG94aFAyVVFyRmtITUtUaHJ4UTcwVmtYWE9OVHp6CkZSeHdrTVUrbTQvUEprS2h2YUdIN1JNdXdLUVk2RTloUHp1ZWo2YVZtYmkwa1BwMmFBRlZaQ1ZZYjdzRjA4eXIKMVRwWFpMTWtvT3YyemxyV2pib01lcHp4VlROdG5rNVBtcGNqdGhPYWk5TXVGT2phWmJmdENocnl4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8c057750-21c2-4b75-9e9c-177f97d7b537.k8s.ondigitalocean.com
  name: do-nyc1-protech
contexts:
- context:
    cluster: do-nyc1-protech
    user: do-nyc1-protech-admin
  name: do-nyc1-protech
current-context: do-nyc1-protech
kind: Config
preferences: {}
users:
- name: do-nyc1-protech-admin
  user:
    token: 4678278bd0a9242b8385c05013d5034f3707323f423f9e2d000ebcdf729b06
