apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEF6TXpFdwpPVE0yTXpGYUZ3MDBNVEF6TXpFd09UTTJNekZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEVSs1dUFoMzg3WnlXNnRmRkJpMlkrYjZEenlPTEdpUjdFYTduWld0dUJOSFRmcVhEbApwOThXVTMxNzhBZThjRkN2SjFkbkVzbm1URTRwM09xTm5aanY0c2VnNVF1bWlNOVV0UHJPWTRscnQzWGlGTDF6CkwwRUFRbXRUV3RhSWtROGVDODlMUE5lanlvSFZIOEo3NHUrZGNJbWdURWh1VzFHcVFhL2NYNkRmNktsNGo0UVoKOWdKNTZPc3BORTY1bTNUWE8zdzJJWnRHTXdTK3l0eldMUDdEd3hORm1ZVXlQejBMWWNoVVNYcG9FR0N6MTNEWgpyeFpQNEJ5OWFPYnhOejF1N0VBUWFkNEhLbDAxMERuRHM4b1BVQm9EMmFtN0VXTGRLd0U5dUlpK3JUUDZvUWpvClJJbWZYQ2laTzVlYllSRm16R3UxUVB6cjF1cEFHdFJ6dm4vRkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFtUndyMlNFTTZIWk9UaUxuRApteVNMOFhWaEREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHS2tHRVRBL1RmbjFsanRLRUFSYTZTandjNHYzClJhR2xCL1d2VHVaVXh3ZWdmZTBEaUt2Y1h6aGczMS9RL1ZodUdSdVNISmcxQy9jZU1pdnhBbHpYV1BXZEJDMEUKeS9sWllPbVZla1hLYzM3dGVMSUx4K0JlaVAvaHkzTVMxTjZXcnVvWGt3L2pDbmR4SzdjWWtyRFNVcTU0N2lUMQpyZWozUGU3Z2RtL3dBYlU1VEpFZWZiS2Y0ZjFBMmFHM2JGWnZHK2xGcUVZeUdPd0hSTThSTU9KSkRLN0lYS3c4CkFLOFdFSzlOdGdYQ0E5RDhpMEZsU2sxeVpLbjNILzg5Y2JmRXI5N0dsVVpFanVITkNvU3Q2TWRyMjkxdlNJNlYKUHZTbE5VQmdQU04rY000RitXc0c3SXFWQUFFYmVrR21pQ1Y3UHVad1d6SThjZHhiTkl1cklnRkZyQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://fd09b5b0-8cc2-4f08-bdde-f035e7f10ba2.k8s.ondigitalocean.com
  name: do-nyc1-pt10
contexts:
- context:
    cluster: do-nyc1-pt10
    user: do-nyc1-pt10-admin
  name: do-nyc1-pt10
current-context: do-nyc1-pt10
kind: Config
preferences: {}
users:
- name: do-nyc1-pt10-admin
  user:
    token: a915f8503a11e2c56c7bc6eaed5815faf3f1ef58951a46c4d4b8ac0693cd6026
