apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEF6TXpFdwpPRFUzTWpoYUZ3MDBNVEF6TXpFd09EVTNNamhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDcHpyVHRpaW5seUlqb04ySStXNGlGUGl2bXJLUnFacDhhZHc2b2kzMWxOZERjMFdoVwp6Q0VFdnRxVGI1ays0bVZFd3VjRmFzek5FK3lYMFJIWHZ3U2RJak5FenhrOS9Fa1NHRGxqa0VRZndaclVhRHdiCm9FVEhoTHgxWE56R2V2OVptaHVSVEcrVmdXTG5MYUg1U1A4WE5lV05tZk03dEZkb3JBWTJscXNXeUN0RlFUUmkKODUzT09XRE96NkE3c1hnSXl4VjNjZmpGL1ZkTlF5cy9xV09USmUxQ2p0VlFlRVFUbnpRbEgrcmNmdkFXc2hEOApPNHhMR2dKc2E2NkFMZnBWb1N0eHhlRUlKeE5HRFV5c3YrUWRPM3grU1lvMHpmSitZTUZlbWtSRTB3aFRQSVd3ClV1R2w5azJOT3gvQUhReWt0U0pMWCswZXk2Z1FvcVp1VDVTekFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJoUVRWalQzaXZpbkpFTXhxWApzb2Q3ckxPbitUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqcU1MWXFFZ1hzNmdFWHM5SGpnOVR6UGQzdkV1Ck10VXlCMkVkUXdxcGpqU25EQ0s1THZtdXV5aElON1RKZE5aVHhIQVRkTDAvbU1yb0RFbDBRL0FtYUp3dDhhUnUKa3dtb2VMR0pmaE9qNExFdSszV1ZjZ2lPR2xqczdRRmJTdWU2b3R2Sm91Sm9LdHdBK3VMRmhCVzN6UCszb2RkZwo0b1crQTBPVitreHAycy9Ddmd4TkthKytzU1UwSHgrNlBwNVdWSHA0aU8vbUl0NkF6dFFoTnNzRVEyWXVCKzhhCkpnV1FoVlMrOFI5MUVxNnYraXhqam91aGdmeVEwWE5RemZGN041czNCUGFreERzQnY1OUZXNWIzZHlVdnRQRm0KN3dsL1BMOGtqRWFTWnFUdkxBN1JLQ1RpUGVFL3Blek1scWZNZDlxTUl4WW40cHYrZzFmcmZ0NkVTUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e6af1b43-b000-4de2-aca4-b3b4a4249d4a.k8s.ondigitalocean.com
  name: do-nyc1-pt5
contexts:
- context:
    cluster: do-nyc1-pt5
    user: do-nyc1-pt5-admin
  name: do-nyc1-pt5
current-context: do-nyc1-pt5
kind: Config
preferences: {}
users:
- name: do-nyc1-pt5-admin
  user:
    token: fada4d6ad1eb7338e00953c3f5a06e89fb04932a43ec4ce57abf990e9dfbdecb
